runtime: nodejs20

entrypoint: node index.js

handlers:
  - url: /static
    static_dir: dist/assignment3-copy/browser # Adjust to match your folder structure

  - url: /
    static_files: dist/assignment3-copy/browser/index.html
    upload: dist/assignment3-copy/browser/index.html
